# error_log ./error.log;
events {}
 
http {
    server {
        listen 80 default_server;
        # access_log ./access.log;

        # server_name ${NGINX_HOST};
        # server_name localhost;

        location / {
            proxy_pass http://localhost:3000;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8000;
        }
        
    }
}

